# Generated by Django 5.1.1 on 2024-10-06 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=150)),
                ('profilepicture', models.ImageField(upload_to='images')),
                ('banner', models.ImageField(blank=True, upload_to='images')),
                ('about', models.TextField()),
                ('phone_number', models.CharField(max_length=150)),
                ('phone_number_2', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter', models.CharField(blank=True, max_length=150)),
                ('fb', models.CharField(blank=True, max_length=150)),
                ('insta', models.CharField(blank=True, max_length=150)),
                ('phone', models.BigIntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
